### PR TITLE
Add icon to sub-repo

### LINKED ISSUE #17: Copy track icon into language track repository
Right now all of the icons used for the language tracks (which can be seen at http://exercism.io/languages) are stored in the exercism/exercism.io repository in `public/img/tracks/`. It would make a lot more sense to keep these images along with all of the other language-specific stuff in each individual language track repository.

There's a pull request that is adding support for serving up the track icon from the x-api, which deals with language-specific stuff.

In order to support this change, each track will need to

- create a directory named `img/` at the root of this repository if it doesn't already exist, then
- find the correct icon in https://github.com/exercism/exercism.io/tree/master/public/img/tracks, and
- stick it in the `img/` directory, and importantly
- **name the image `icon.png`**

In other words, at the end of it you should have the following file:

```
./img/icon.png
```

See https://github.com/exercism/exercism.io/issues/2925 for more details.

### PR DESCRIPTION
**Pull request by cmc333333**
Resolves #17

### CODE REVIEW

**Comment by kytrinyx** [comment]
I'm so sorry I missed this. Thanks for the contribution, @cmc333333!

**Comment by dom96** [comment]
This is a very cool reinterpretation of the original logo, I like it :)

**Comment by kytrinyx** [comment]
@dom96 We tried figuring out the licensing of the logo... https://github.com/exercism/exercism.io/blob/master/ATTRIBUTION.md If you happen to know the truth of the matter, would you holler?

**Comment by dom96** [comment]
Well, there is this: https://github.com/nim-lang/assets/blob/master/Art/README.md

But it doesn't feel very clear to me. I created an issue in any case: https://github.com/nim-lang/assets/issues/5

**Comment by kytrinyx** [comment]
Ah, sweet. Thanks @dom96!

**Pull request merged**
