### PR TITLE
Add "hello-world" exercise

### PR DESCRIPTION
**Pull request by cmc333333**

### CODE REVIEW

**Comment by kytrinyx** [comment]
Thank you! :heart:

**Comment by kytrinyx** [comment]
I'll be deploying this to the website today.

**Comment by cmc333333** [comment]
@kytrinyx excellent. It felt suspiciously easy to contribute, so please let me know if I missed a step!

**Comment by kytrinyx** [comment]
No, you got it in one :) a test file and a sample solution with /example/i in the name.

**Comment by cmc333333** [comment]
@kytrinyx I'm not seeing the exercise here: http://exercism.io/languages/nim -- sure I didn't make a mistake?

**Comment by kytrinyx** [comment]
Uh... I think I forgot to deploy. One sec!

**Comment by kytrinyx** [comment]
And deployed.

**Pull request merged**
